[build]
  command = "export NODE_OPTIONS='--openssl-legacy-provider' && npm install && npm run build"
  functions = "functions"

 [[redirects]]
   from = "/*"
   to = "/.netlify/functions/app/:splat"
   status = 200
